/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-04-11 13:23:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class category_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/MR/Desktop/LinhWine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LinhWine/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Users/MR/Desktop/LinhWine/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LinhWine/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1649392875515L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Danh sách sản phẩm</title>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<main id=\"main\" class=\"\">\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"shop-page-title category-page-title page-title \">\r\n");
      out.write("            <div class=\"page-title-inner flex-row  medium-flex-wrap container\">\r\n");
      out.write("                <div class=\"flex-col flex-grow medium-text-center\">\r\n");
      out.write("                    <h1 class=\"shop-page-title is-xlarge categorycustom\">Danh sách sản phẩm</h1>\r\n");
      out.write("                    <div class=\"is-small\">\r\n");
      out.write("                        <nav class=\"woocommerce-breadcrumb breadcrumbs \"><a href=\"/\">Trang chủ</a> <span class=\"divider\">/</span><span class=\"categorycustom\"><firstletter>Iphone</firstletter></span></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"category-filtering category-filter-row show-for-medium\">\r\n");
      out.write("                        <a href=\"#\" data-open=\"#shop-sidebar\" data-visible-after=\"true\" data-pos=\"left\" class=\"filter-button uppercase plain\">\r\n");
      out.write("                            <i class=\"icon-equalizer\"></i>\r\n");
      out.write("                            <strong>Lọc</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"inline-block\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex-col medium-text-center\">\r\n");
      out.write("                    <form class=\"woocommerce-ordering\" method=\"post\" enctype=\"multipart/form-data\" action=\"/SanPham/XemSanPhamTheoDanhMuc/1\">\r\n");
      out.write("                        <select name=\"loc\" class=\"orderby\" aria-label=\"Đơn hàng của cửa hàng\">\r\n");
      out.write("                            <option name=\"loc\" value=\"menu_order\" selected=\"selected\">Thứ tự mặc định</option>\r\n");
      out.write("                                <option name=\"loc\" value=\"tang\">Theo giảm giá: thấp đến cao</option>\r\n");
      out.write("                                                    <option name=\"loc\" value=\"giam\">Theo giảm giá: cao xuống thấp</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                \r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("            <div class=\"row category-page-row\" style=\"display: flex; justify-content: center;\">\r\n");
      out.write("                <div class=\"col large-9\">\r\n");
      out.write("                    <div class=\"shop-container\">\r\n");
      out.write("        \r\n");
      out.write("                        <div class=\"woocommerce-notices-wrapper\"></div>\r\n");
      out.write("                        <div class=\"products row row-small large-columns-4 medium-columns-3 small-columns-2 has-equal-box-heights equalize-box\">\r\n");
      out.write("                                \r\n");
      out.write("                             ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("                             \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <nav class=\"woocommerce-pagination\">\r\n");
      out.write("                                <div class=\"pagination-container\"><ul class=\"text-center links nav-pagination page-numbers\"><li class=\"page-number active\"><a>1</a></li><li class=\"page-number\"><a href=\"/SanPham/XemSanPhamTheoDanhMuc/1?page=2\">2</a></li><li class=\"page-number\"><a href=\"/SanPham/XemSanPhamTheoDanhMuc/1?page=3\">3</a></li><li class=\"page-number\"><a href=\"/SanPham/XemSanPhamTheoDanhMuc/1?page=4\">4</a></li><li class=\"page-number PagedList-skipToNext\"><a href=\"/SanPham/XemSanPhamTheoDanhMuc/1?page=2\" rel=\"next\">»</a></li></ul></div>\r\n");
      out.write("                   \r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- shop container -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("                </main>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/category.jsp(48,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/user/category.jsp(48,29) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/category.jsp(48,29) '${products }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${products }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                             \r\n");
            out.write("                             	");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                             \r\n");
            out.write("                             ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/user/category.jsp(50,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id_category == idCategory }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                             		\r\n");
          out.write("                             		<div class=\"product-small col has-hover product type-product post-7098 status-publish first instock product_cat-bo-duong-da product_cat-my-pham-duong-da has-post-thumbnail sale shipping-taxable purchasable product-type-simple\">\r\n");
          out.write("	                                    <div class=\"col-inner\">\r\n");
          out.write("	                                        <div class=\"absolute left top z-1\">\r\n");
          out.write("	                                            <div class=\"callout badge badge-circle\">\r\n");
          out.write("	                                                <div class=\"badge-inner secondary on-sale\"><span class=\"onsale\">-4 %</span></div>\r\n");
          out.write("	                                            </div>\r\n");
          out.write("	                                        </div>\r\n");
          out.write("	                                        <div class=\"product-small box \">\r\n");
          out.write("	                                            <div class=\"box-image\">\r\n");
          out.write("	                                                <div class=\"image-zoom\">\r\n");
          out.write("	                                                    <a href=\"#\">\r\n");
          out.write("	                                                        <img width=\"247\" height=\"247\" style=\"max-height:247px\" src=\"images/img/iphone_11_white_4.jpg\" class=\"attachment-woocommerce_thumbnail size-woocommerce_thumbnail lazy-load-active\" alt=\"\" loading=\"lazy\" sizes=\"(max-width: 247px) 100vw, 247px\">\r\n");
          out.write("	                                                    </a>\r\n");
          out.write("	                                                </div>\r\n");
          out.write("	                                                <div class=\"image-tools is-small top right show-on-hover\">\r\n");
          out.write("	                                                </div>\r\n");
          out.write("	                                                <div class=\"image-tools is-small hide-for-small bottom left show-on-hover\">\r\n");
          out.write("	                                                </div>\r\n");
          out.write("	                                                <div class=\"image-tools grid-tools text-center hide-for-small bottom hover-slide-in show-on-hover\">\r\n");
          out.write("	                                                </div>\r\n");
          out.write("	                                            </div>\r\n");
          out.write("	        \r\n");
          out.write("	                                            <div class=\"box-text box-text-products text-center grid-style-2\">\r\n");
          out.write("	                                                <div class=\"title-wrapper\">\r\n");
          out.write("	                                                    <p class=\"name product-title woocommerce-loop-product__title\" style=\"height: 56.1111px;\"><a href=\"#\" class=\"woocommerce-LoopProduct-link woocommerce-loop-product__link\">iPhone 11 128GB I Chính hãng VN/A</a></p>\r\n");
          out.write("	                                                </div>\r\n");
          out.write("	                                                <div class=\"price-wrapper\" style=\"height: 13.3333px;\">\r\n");
          out.write("	                                                    <span class=\"price\">\r\n");
          out.write("	                                                        <del>\r\n");
          out.write("	                                                            <span class=\"woocommerce-Price-amount amount\">\r\n");
          out.write("	                                                                <bdi>19.900.000<span class=\"woocommerce-Price-currencySymbol\">₫</span></bdi>\r\n");
          out.write("	                                                            </span>\r\n");
          out.write("	                                                        </del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi>19.000.000<span class=\"woocommerce-Price-currencySymbol\">₫</span></bdi></span></ins>\r\n");
          out.write("	                                                    </span>\r\n");
          out.write("	                                                </div>\r\n");
          out.write("	                                            </div>\r\n");
          out.write("	                                        </div>\r\n");
          out.write("	                                    </div>\r\n");
          out.write("	                                </div>\r\n");
          out.write("                             	\r\n");
          out.write("                             	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
